export const INITIAL_CATEGORIES = [
  // Main Categories
  {
    nameAr: 'سيارات',
    nameEn: 'Vehicles',
    slug: 'vehicles',
    icon: 'DirectionsCar',
    order: 1,
    children: [
      { nameAr: 'سيارات للبيع', nameEn: 'Cars for Sale', slug: 'cars-for-sale', order: 1 },
      { nameAr: 'قطع غيار', nameEn: 'Spare Parts', slug: 'spare-parts', order: 2 },
      { nameAr: 'دراجات نارية', nameEn: 'Motorcycles', slug: 'motorcycles', order: 3 },
      { nameAr: 'شاحنات', nameEn: 'Trucks', slug: 'trucks', order: 4 },
      { nameAr: 'معدات ثقيلة', nameEn: 'Heavy Equipment', slug: 'heavy-equipment', order: 5 },
    ],
  },
  {
    nameAr: 'عقارات',
    nameEn: 'Real Estate',
    slug: 'real-estate',
    icon: 'Home',
    order: 2,
    children: [
      { nameAr: 'شقق للبيع', nameEn: 'Apartments for Sale', slug: 'apartments-sale', order: 1 },
      { nameAr: 'شقق للإيجار', nameEn: 'Apartments for Rent', slug: 'apartments-rent', order: 2 },
      { nameAr: 'فلل للبيع', nameEn: 'Villas for Sale', slug: 'villas-sale', order: 3 },
      { nameAr: 'فلل للإيجار', nameEn: 'Villas for Rent', slug: 'villas-rent', order: 4 },
      { nameAr: 'أراضي', nameEn: 'Land', slug: 'land', order: 5 },
      { nameAr: 'عمارات', nameEn: 'Buildings', slug: 'buildings', order: 6 },
      { nameAr: 'محلات تجارية', nameEn: 'Commercial', slug: 'commercial', order: 7 },
    ],
  },
  {
    nameAr: 'الكترونيات',
    nameEn: 'Electronics',
    slug: 'electronics',
    icon: 'Devices',
    order: 3,
    children: [
      { nameAr: 'جوالات', nameEn: 'Mobile Phones', slug: 'mobile-phones', order: 1 },
      { nameAr: 'أجهزة كمبيوتر', nameEn: 'Computers', slug: 'computers', order: 2 },
      { nameAr: 'لابتوب', nameEn: 'Laptops', slug: 'laptops', order: 3 },
      { nameAr: 'تابلت', nameEn: 'Tablets', slug: 'tablets', order: 4 },
      { nameAr: 'كاميرات', nameEn: 'Cameras', slug: 'cameras', order: 5 },
      { nameAr: 'ألعاب فيديو', nameEn: 'Gaming', slug: 'gaming', order: 6 },
      { nameAr: 'أجهزة منزلية', nameEn: 'Home Appliances', slug: 'home-appliances', order: 7 },
    ],
  },
  {
    nameAr: 'أثاث ومفروشات',
    nameEn: 'Furniture',
    slug: 'furniture',
    icon: 'Weekend',
    order: 4,
    children: [
      { nameAr: 'غرف نوم', nameEn: 'Bedrooms', slug: 'bedrooms', order: 1 },
      { nameAr: 'غرف معيشة', nameEn: 'Living Rooms', slug: 'living-rooms', order: 2 },
      { nameAr: 'غرف طعام', nameEn: 'Dining Rooms', slug: 'dining-rooms', order: 3 },
      { nameAr: 'مكاتب', nameEn: 'Office Furniture', slug: 'office', order: 4 },
      { nameAr: 'ديكور منزلي', nameEn: 'Home Decor', slug: 'home-decor', order: 5 },
    ],
  },
  {
    nameAr: 'أزياء وموضة',
    nameEn: 'Fashion',
    slug: 'fashion',
    icon: 'Checkroom',
    order: 5,
    children: [
      { nameAr: 'ملابس رجالية', nameEn: "Men's Clothing", slug: 'mens-clothing', order: 1 },
      { nameAr: 'ملابس نسائية', nameEn: "Women's Clothing", slug: 'womens-clothing', order: 2 },
      { nameAr: 'ملابس أطفال', nameEn: "Kids' Clothing", slug: 'kids-clothing', order: 3 },
      { nameAr: 'أحذية', nameEn: 'Shoes', slug: 'shoes', order: 4 },
      { nameAr: 'ساعات', nameEn: 'Watches', slug: 'watches', order: 5 },
      { nameAr: 'إكسسوارات', nameEn: 'Accessories', slug: 'accessories', order: 6 },
    ],
  },
  {
    nameAr: 'رياضة وترفيه',
    nameEn: 'Sports & Leisure',
    slug: 'sports-leisure',
    icon: 'SportsBasketball',
    order: 6,
    children: [
      { nameAr: 'معدات رياضية', nameEn: 'Sports Equipment', slug: 'sports-equipment', order: 1 },
      { nameAr: 'دراجات هوائية', nameEn: 'Bicycles', slug: 'bicycles', order: 2 },
      { nameAr: 'معدات تخييم', nameEn: 'Camping', slug: 'camping', order: 3 },
      { nameAr: 'صيد', nameEn: 'Fishing', slug: 'fishing', order: 4 },
    ],
  },
  {
    nameAr: 'خدمات',
    nameEn: 'Services',
    slug: 'services',
    icon: 'MiscellaneousServices',
    order: 7,
    children: [
      { nameAr: 'خدمات تنظيف', nameEn: 'Cleaning Services', slug: 'cleaning', order: 1 },
      { nameAr: 'صيانة', nameEn: 'Maintenance', slug: 'maintenance', order: 2 },
      { nameAr: 'نقل', nameEn: 'Moving', slug: 'moving', order: 3 },
      { nameAr: 'تصميم', nameEn: 'Design', slug: 'design', order: 4 },
      { nameAr: 'تعليم', nameEn: 'Education', slug: 'education', order: 5 },
    ],
  },
  {
    nameAr: 'وظائف',
    nameEn: 'Jobs',
    slug: 'jobs',
    icon: 'Work',
    order: 8,
    children: [
      { nameAr: 'وظائف شاغرة', nameEn: 'Job Vacancies', slug: 'vacancies', order: 1 },
      { nameAr: 'باحث عن عمل', nameEn: 'Job Seekers', slug: 'seekers', order: 2 },
    ],
  },
  {
    nameAr: 'حيوانات',
    nameEn: 'Animals',
    slug: 'animals',
    icon: 'Pets',
    order: 9,
    children: [
      { nameAr: 'قطط', nameEn: 'Cats', slug: 'cats', order: 1 },
      { nameAr: 'كلاب', nameEn: 'Dogs', slug: 'dogs', order: 2 },
      { nameAr: 'طيور', nameEn: 'Birds', slug: 'birds', order: 3 },
      { nameAr: 'مواشي', nameEn: 'Livestock', slug: 'livestock', order: 4 },
      { nameAr: 'خيول', nameEn: 'Horses', slug: 'horses', order: 5 },
    ],
  },
  {
    nameAr: 'متنوعات',
    nameEn: 'Miscellaneous',
    slug: 'miscellaneous',
    icon: 'Category',
    order: 10,
    children: [
      { nameAr: 'كتب', nameEn: 'Books', slug: 'books', order: 1 },
      { nameAr: 'ألعاب أطفال', nameEn: 'Toys', slug: 'toys', order: 2 },
      { nameAr: 'مستلزمات أطفال', nameEn: 'Baby Items', slug: 'baby-items', order: 3 },
      { nameAr: 'أخرى', nameEn: 'Other', slug: 'other', order: 4 },
    ],
  },
] as const;
